ASSETS_DIR = "/code/src/ROS/assets"

HEADING_MODEL_PATH = f"{ASSETS_DIR}/rllib_db21j_multi_engine_655360_heading.onnx"
HEADING_MODEL_METADATA_PATH = f"{HEADING_MODEL_PATH}.json"
HEADING_OBS_HEIGHT = 84
HEADING_OBS_WIDTH = 84
HEADING_FRAME_STACK = 3
HEADING_CROP_TOP_RATIO = 0.33
HEADING_OBSERVATION_MODE = "binary_lane"
HEADING_FORWARD_SPEED = 0.5
HEADING_GAIN = 1.0
HEADING_MAX_STEER = 1.0
HEADING_TYPE = "heading_clipped_08"
HEADING_PROCESS_EVERY_N_FRAMES = 1
