ASSETS_DIR = "/code/src/ROS/assets"

YOLO_MODEL_PATH = f"{ASSETS_DIR}/myyolo11n.pt"
IMAGE_SIZE = 640

HEADING_MODEL_PATH = f"{ASSETS_DIR}/rllib_db21j_multi_engine_712704_heading.onnx"
HEADING_MODEL_METADATA_PATH = f"{HEADING_MODEL_PATH}.json"
HEADING_OBS_HEIGHT = 84
HEADING_OBS_WIDTH = 84
HEADING_FRAME_STACK = 3
HEADING_CROP_TOP_RATIO = 0.33
HEADING_FORWARD_SPEED = 0.5
HEADING_GAIN = 1.0
HEADING_MAX_STEER = 1.0
HEADING_TYPE = "heading_smooth"
HEADING_PROCESS_EVERY_N_FRAMES = 1
